only update the meta git submodule

diff --git a/install-profile b/install-profile
--- a/install-profile
+++ b/install-profile
@@ -7,7 +7,7 @@
 # ./install-profile mac
 # ./install-profile debian-terminal
 # ./install-profile debian-terminal debian-gui
-# 
+#
 # ------------------------------------------------------------------------------------------------ #
 #
 # files in ./meta/profiles/ folder are plain text files that have config filename(no file extenstion).
@@ -17,24 +17,24 @@
 # nvim
 # tmux
 # homebrew
-# 
+#
 # ------------------------------------------------------------------------------------------------ #
 #
 # NOTE: to run a config in sudo, then add '-sudo' as a suffix of the config to run.
 # Ex: ./meta/profiles/debian contains
 # apt-sudo
-# 
+#
 # ------------------------------------------------------------------------------------------------ #
-# 
+#
 # to ignore a line in a profile, add '#' at the beginning of that line
 # Ex: ./meta/profiles/macos contains
 # nvim
 # tmux
 # homebrew
 # # astronvim
-# 
+#
 # This will ignore 'astronvim' config
-# 
+#
 # ------------------------------------------------------------------------------------------------ #
 #
 # check example: https://github.com/ecarlson94/dotbot-template/blob/main/meta/profiles/exampleOS1
@@ -52,7 +52,7 @@ PROFILES_DIR="profiles"
 BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 cd "${BASE_DIR}"
-git submodule update --init --recursive
+git submodule update --init --recursive meta/
 
 # ------------------------------------------------------------------------------------------------ #
 # Utility functions
@@ -61,38 +61,38 @@ git submodule update --init --recursive
 # used for segmenting when a profile configs is being executed.
 # For VISUAL purposes
 printLineBanner() {
-  # print a line depending on the terminal width
-  # https://unix.stackexchange.com/a/425158
-  # https://stackoverflow.com/a/17030976/3053548
-  #
-  # print ANSI color using printf
-  # https://stackoverflow.com/a/26873040/3053548
-  printf '\e[1;34m%0.s#\e[0m' $(seq 1 $(stty size | awk '{print $2}'))
+	# print a line depending on the terminal width
+	# https://unix.stackexchange.com/a/425158
+	# https://stackoverflow.com/a/17030976/3053548
+	#
+	# print ANSI color using printf
+	# https://stackoverflow.com/a/26873040/3053548
+	printf '\e[1;34m%0.s#\e[0m' $(seq 1 $(stty size | awk '{print $2}'))
 }
 
 # ------------------------------------------------------------------------------------------------ #
 # Verify dotbot profile exists
 # Checks if the file exists in meta/profiles/ folder
 
-exitIfProfileNotFound=false    # used as a flag to exit IF a profile is NOT found
+exitIfProfileNotFound=false # used as a flag to exit IF a profile is NOT found
 for profile in ${@}; do
-  # check if the profile filepath doesn't exist
-  #   print message
-  #   flag variable to exit
+	# check if the profile filepath doesn't exist
+	#   print message
+	#   flag variable to exit
 
-  profileFilepath="${BASE_DIR}/${META_DIR}/${PROFILES_DIR}/${profile}"
+	profileFilepath="${BASE_DIR}/${META_DIR}/${PROFILES_DIR}/${profile}"
 
-  if [[ ! -e $profileFilepath ]]; then
-    echo -e "Dotbot profile \\033[1;31m$profileFilepath \\033[0mNOT found"
+	if [[ ! -e $profileFilepath ]]; then
+		echo -e "Dotbot profile \\033[1;31m$profileFilepath \\033[0mNOT found"
 
-    exitIfProfileNotFound=true
-  fi
+		exitIfProfileNotFound=true
+	fi
 done
 
 # exit if a profile filepath is NOT found
 if [[ $exitIfProfileNotFound == true ]]; then
-  echo -e "\nexiting"
-  exit 1
+	echo -e "\nexiting"
+	exit 1
 fi
 
 # cleanup variables
@@ -105,27 +105,26 @@ unset exitIfProfileNotFound
 #   extract dotbot configs to run
 #   run dotbot configs using ./install-standalone
 for profile in ${@}; do
-    # extract dotbot configs to run
-    while IFS= read -r config; do
-        CONFIGS+=" ${config}"
+	# extract dotbot configs to run
+	while IFS= read -r config; do
+		CONFIGS+=" ${config}"
 
-    # read lines that DON'T start with #
-    # obtained from https://stackoverflow.com/a/8197412/3053548
-    done < <(grep -v '^#' "${META_DIR}/${PROFILES_DIR}/$profile")
+		# read lines that DON'T start with #
+		# obtained from https://stackoverflow.com/a/8197412/3053548
+	done < <(grep -v '^#' "${META_DIR}/${PROFILES_DIR}/$profile")
 
-    # print line banner multiple times
-    # https://serverfault.com/a/273241
-    for i in `seq 2`; do printLineBanner; done
-    echo -e "\nRunning profile \e[1;34m$profile\e[0m\n"
+	# print line banner multiple times
+	# https://serverfault.com/a/273241
+	for i in $(seq 2); do printLineBanner; done
+	echo -e "\nRunning profile \e[1;34m$profile\e[0m\n"
 
-    # run profile configs
-    source ./install-standalone ${CONFIGS}
+	# run profile configs
+	source ./install-standalone ${CONFIGS}
 
-    # cleanup variables
-    unset CONFIGS
+	# cleanup variables
+	unset CONFIGS
 done
 
 cd "${BASE_DIR}"
 
 echo "Restart your terminal..."
-
